### ISSUE TITLE
Замечания по Product Vision и User Stories

### ISSUE THREAD

**Issue by nvamelichev** [hypersousage/console-organizer#1]
- Product Vision:
    - Пока что вИдение читается как "декларация о намерениях": "мы сделаем такое-то и такое-то". Но нигде не сказано, зачем это делать и для кого. (Ответ: "потому что мы взяли такое задание" и "для преподавателя" &mdash; очевидный, но не подходит :-D)
    - Нужно указать, кто потенциальные пользователи продукта. Написать, какую боль продукт им облегчит/какую ценность создаст.
    - Нужно продумать и указать, с какими рисками может столкнуться проект. Почему проект может не осуществиться в той форме, в которой задуман? Почему сроки реализации могут "съехать"? Насколько вероятно, что эти риски осуществятся? Насколько разрушительными будут последствия?
    - Я правильно понимаю, что scope проекта - только управление TODOшками, а всякие регулярные встречи/дни рождения/карточки контактов и т.д. остаётся за кадром? (Это не предложение добавить в ваш проект всё это, а предложение объяснить, почему именно такой набор фич вам представляется самым необходимым.)
- User Stories:
    - Одну большую историю ("как разраб-любитель консоли, я хочу быть здоровым и богатым") нужно разбить на несколько, описанных чуть более подробно (например, про теги-категории, приоритеты, напоминашки и т.д.). Совсем хорошо, если истории будут для разных классов пользователей, и не все из этих пользователей будут хардкорными "разработчиками, не вылезающими из консоли".

**Comment by nvamelichev** [comment]
@hypersousage ^^^

**Comment by hypersousage** [comment]
Поправили замечания
